=== DiamondMofeng/HFUT-AutoSignGUI/XMLTasks.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="TaskList">
	<xs:complexType>
		<xs:sequence>

			<xs:element name="Task" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:sequence>

						<xs:element name="account" type="xs:string"/>
						<xs:element name="solution" type="xs:string"/>
						<xs:element name="time" type="xs:string"/>

					</xs:sequence>
					<xs:attribute name="id" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>

		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== DiamondMofeng/HFUT-AutoSignGUI/XMLTasks.xml
<?xml version="1.0" encoding="utf-8"?>
<TaskList
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="XMLTasks.xsd">
	<Task id="Test">
		<account>2019123456</account>
		<solution>mode</solution>
		<time>hh:mm</time>
	</Task>
	
	<Task id="Test2">
		<account>2019123456</account>
		<solution>mode</solution>
		<time>hh:mm</time>
	</Task>
	<Task id="">
		<account>2019123456</account>
		<solution>
		</solution>
		<time>14:50</time>
	</Task>
</TaskList>
